-- Query 1: List all patients with their doctors and appointment details
SELECT P.FIRST_NAME || ' ' || P.LAST_NAME AS PATIENT_NAME,
       D.FIRST_NAME || ' ' || D.LAST_NAME AS DOCTOR_NAME,
       A.APPOINTMENT_DATE, A.STATUS
FROM APPOINTMENTS A
JOIN PATIENTS P ON A.PATIENT_ID = P.PATIENT_ID
JOIN DOCTORS D ON A.DOCTOR_ID = D.DOCTOR_ID;

-- Query 2: Show the most expensive treatment
SELECT TREATMENT_TYPE, DESCRIPTION, COST
FROM TREATMENTS
WHERE COST = (SELECT MAX(COST) FROM TREATMENTS);

-- Query 3: Find doctors who have no appointments
SELECT D.FIRST_NAME || ' ' || D.LAST_NAME AS DOCTOR_NAME, D.SPECIALIZATION
FROM DOCTORS D
WHERE D.DOCTOR_ID NOT IN (SELECT DOCTOR_ID FROM APPOINTMENTS);

-- Query 4: Find patients who have appointments but did not attend (no treatments, status still Scheduled)
SELECT DISTINCT P.FIRST_NAME || ' ' || P.LAST_NAME AS PATIENT_NAME
FROM PATIENTS P
JOIN APPOINTMENTS A ON P.PATIENT_ID = A.PATIENT_ID
WHERE A.STATUS = 'Scheduled'
AND A.APPOINTMENT_ID NOT IN (SELECT APPOINTMENT_ID FROM TREATMENTS);

-- Query 5: Show top 3 most prescribed medicines
SELECT M.NAME, COUNT(PR.MEDICINE_ID) AS TIMES_PRESCRIBED
FROM PRESCRIPTIONS PR
JOIN MEDICINES M ON PR.MEDICINE_ID = M.MEDICINE_ID
GROUP BY M.NAME
ORDER BY TIMES_PRESCRIBED DESC
FETCH FIRST 3 ROWS ONLY;

-- Query 6: Calculate total revenue per doctor from paid bills
SELECT D.FIRST_NAME || ' ' || D.LAST_NAME AS DOCTOR_NAME,
       SUM(B.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM BILLS B
JOIN APPOINTMENTS A ON B.APPOINTMENT_ID = A.APPOINTMENT_ID
JOIN DOCTORS D ON A.DOCTOR_ID = D.DOCTOR_ID
WHERE B.PAYMENT_STATUS = 'Paid'
GROUP BY D.FIRST_NAME, D.LAST_NAME
ORDER BY TOTAL_REVENUE DESC;